apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
    statefulset.kubernetes.io/pod-name: postgres-postgresql-0
